### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by jingchangshi** [wme7/cprlinearexamples#1]
I execute `FR_CPR2d_linearAdvection_eg1.m` and get ths following error.

```
Warning: Name is nonexistent or not a directory: ~\github\Research-Matlab\DGFEM\FEMmesh 
> In path (line 109)
  In addpath (line 86)
  In DGmeshQuad (line 392)
  In FR_CPR2d_linearAdvection_eg1 (line 57) 
Undefined function or variable 'Q4meshGenerator'.
```

**Comment by wme7** [comment]
Hi desperadoshi, 
It seems that Matlab cannot find my quadrilateral Mesher function. 
I recall that it worked perfectly in Matlab 2013b.
Let me take a look to see what's going on ; )

**Comment by jingchangshi** [comment]
@wme7 Hi! Are you working on FR/CPR as a PhD? And would you like to give your publication wepage? I'm just starting this topic.

**Comment by wme7** [comment]
@desperadoshi Hi there! 
You were right. A function was missing. My apologies!
Please update the fork so you can have the new changes. 
Indeed, I was working on CPR as a PhD. I used this code for solving Boltzmann-BGK model equation. 
http://dx.doi.org/10.4208/cicp.171214.210715s . FR/CPR is a very nice, still a lot of work has to be done in modeling solutions with discontinuities. Wish you all the best! ; )

**Comment by jingchangshi** [comment]
@wme7 Great! A fellow PhD in my group is working on UGKS, but not by FR/CPR. I'm surprised to know such a field CPR would be employed. Wish you all the best too!

**Comment by wme7** [comment]
@desperadoshi UGKS, really? nice!
are you working with Prof. Xu Kun?

**Comment by jingchangshi** [comment]
@wme7 Yes, he is working on UGKS. And we are in a university in China Mainland, but my fellow PhD mentioned above is now studying in HongKong as a Visiting Student supported by Prof. Xu Kun. And I hope he could learn the most from Prof. Xu Kun.

**Comment by wme7** [comment]
@desperadoshi that's good to hear. Prof. Xu is doing a lot of work on nodal DG (a close partner of FR/CPR) nowadays to approach Boltzmann solutions. He was the editor in charge of the paper I just shared with you. Moreover, I'm currently working not to far from mainland China, I'm in Taiwan ; )
I leave open doors if any question, I'll do my best to see if I can help you. All the best!

**Comment by jingchangshi** [comment]
@wme7 it's very nice of you! Thank you!
